config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, presence: true  #messageが空ではない
  validates :message, length: {maximum: 140}  #140字以下
  
  def hello2
    logger.debug "Model"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    logger.debug "application_controller"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    #hello #↓コントローラ・モデルの継承
    #logger.debug "test"
    #Tweet.new.hello2
  end
  
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(message: params[:tweet][:message], tdate:Time.current)
    if @tweet.save
      flash[:notice] = '1レコード追加しました'
     redirect_to root_path
    else
     render 'new'
    end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    tweet.update(message: params[:tweet][:message])
    redirect_to root_path
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>L1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <div id="header">
      <%= render "header" %>
    </div>
    <div id="sidebar">
      <%= render "sidebar" %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render "footer" %>
    </div>
  </div>

</body>
</html>

app/views/tweets/_footer.html.erb
<p>&copy; 2018 Twitter&ensp;
  <a href="https://about.twitter.com/ja.html" class="footerLink">Twitterについて&ensp;</a>
  <br><a href="https://help.twitter.com/ja" class="footerLink">ヘルプセンター&ensp;</a>
  <a href="https://twitter.com/tos" class="footerLink">規約&ensp;</a>
  <a href="https://twitter.com/privacy" class="footerLink">プライバシーポリシー&ensp;</a>
  <br><a href="https://support.twitter.com/articles/20170514" class="footerLink">クッキー&ensp;</a>
  <a href="https://support.twitter.com/articles/20170451" class="footerLink">広告について&ensp;</a>
</p>

app/views/tweets/_form.html.erb
<%= f.label :message, 'ツイート本文' %>
<p><%= f.text_area :message, rows: 5, cols: 70 %></p>
<%= f.submit 'ツイート' %>

app/views/tweets/_header.html.erb
<div id="headerBar">
    <img src="/assets/icon.jpg", id="headerIcon">
    <%= link_to 'ツイート', new_tweet_path, id: "tweetBtn" %>
</div>

<img src="/assets/header.jpg", id="headerImage">
<img src="/assets/icon.jpg", id="icon">

app/views/tweets/_sidebar.html.erb
<h2>近畿大学</h2>
<p class="gray">@kinkidaigakuPR</p>
近畿大学総務部広報室のTwitter公式アカウントです。近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。 個別DMでのお問い合わせには返信を行っておりませんので、ご了承ください。
<p class="gray">◎　大阪府東大阪市
<br><a href="https://t.co/93yqCB7Cqv", id="url">instagram.com/kinkidaigakupr/</a>
<br>2010年12月に登録</p>

<p>
  <%= link_to "ツイート", new_tweet_path, class: "btn" %>
  <%= link_to "ダイレクト...", new_tweet_path, class: "btn" %>
</p>

app/views/tweets/edit.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @tweet, :url=>{action: :update} do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/tweets/index.html.erb
<head>
 <meta charset="utf-8">
 <link href="application.css" rel="stylesheet">
</head>

<body>
 <% @tweets.each do |t| %>
  <div id="tweets">
  <img src="/assets/icon.jpg">
  <p><span id="name">近畿大学</span>
  <span class="gray">@kinkidaigakuPR - <%= (Time.current - t.tdate).to_i / 60 %>分前</span>
  <br><%= t.message %>
  <br><%= link_to '表示', tweet_path(t) %>
  <%= link_to '削除', tweet_path(t), method: :delete %>
  <%= link_to '編集', edit_tweet_path(t) %>
  </p></div><hr>
 <% end %>
</body>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @tweet, :url=>{action: :create} do |f| %>
 <%= render "form", f: f %>
<% end %>

app/views/tweets/show.html.erb
<p>
    <%= @tweet.message %>
</p>
<p>
    <%= (Time.current - @tweet.tdate).to_i / 60 %>分前
</p>
<%= link_to '戻る', '/' %>